### ISSUE TITLE
Problems running the codes

### ISSUE THREAD

**Issue by WangYuxuan93** [zjiehang/DPAttack#1]
Hi, guys,
I have been trying to run the code based on my understanding but there seem to be some problems. Below is what I have done so far.
1. I have trained a biaffine parser (Word-based without POS tag) with the codes which achieved UAS=95.71, LAS=93.72 at PTB test set. (this is very close to the clean results from the paper UAS=95.52.)
2. I have attacked it using the 'blackbox' mode (defined in dpattack.cmds.zeng.blackbox.blackbox) with the default config file (https://github.com/zjiehang/DPAttack/blob/master/config.ini) and changed blackbox_method = substitute, revised_rate = 0.15. 
But the attacked results are UAS=82.96 and LAS=80.71, which is much different from the results in the paper (UAS=88.69). 

Could you provide some help to tell me where the problem is?

**Comment by zjiehang** [comment]
I'm sorry, I recently worked as an intern in Alibaba Group, and I don't have enough time to reconstruct my code. I make sure that I can reconstruct the code and give more instruction for this code after this August. You can provide me with your code and result, and I will check it for you. Send it to email: jhzeng18@fudan.edu.cn.
By the way, there are some constraints in black-box attack, including bert-generator, pos-tagger filter, and only replacing nouns, verbs, adjective, adverb.
Hope it can help you!
