### ISSUE TITLE
Is there any data provided?

### ISSUE THREAD

**Issue by insomnia1996** [zjiehang/DPAttack#2]
Hi guys, I'm interested in your great work and thanks for sharing your code. Can you provide a link for downloading your dataset? Or can you tell me is there any preprocess for your PTB dataset except Stanford Dependency Converter?
Thanks in advance!

**Comment by zjiehang** [comment]
> Hi guys, I'm interested in your great work and thanks for sharing your code. Can you provide a link for downloading your dataset? Or can you tell me is there any preprocess for your PTB dataset except Stanford Dependency Converter?
> Thanks in advance!

Hi,
the dataset used is uploaded in https://drive.google.com/file/d/1T7euYsYkYAv26IUGZx-Bn4QqkWjQhDO8/view?usp=sharing, where the Stanford Dependency Converter 3.3.0 is used here.

Note that when preprocessing data, we ask for the copula (linking verbs) to remain the head when its complement is an adjective or noun, seeing Section 4.7 in Stanford typed dependencies manual (url: https://nlp.stanford.edu/software/dependencies_manual.pdf)

**Comment by insomnia1996** [comment]
> > Hi guys, I'm interested in your great work and thanks for sharing your code. Can you provide a link for downloading your dataset? Or can you tell me is there any preprocess for your PTB dataset except Stanford Dependency Converter?
> > Thanks in advance!
> 
> Hi,
> the dataset used is uploaded in https://drive.google.com/file/d/1T7euYsYkYAv26IUGZx-Bn4QqkWjQhDO8/view?usp=sharing, where the Stanford Dependency Converter 3.3.0 is used here.
> 
> Note that when preprocessing data, we ask for the copula (linking verbs) to remain the head when its complement is an adjective or noun, seeing Section 4.7 in Stanford typed dependencies manual (url: https://nlp.stanford.edu/software/dependencies_manual.pdf)

Thanks for providing your data! BTW, which one do you use as your dataset, LDC2012T13(English web treebank) or LDC99T42(treebank 3.0) ?

**Comment by zjiehang** [comment]
> treebank 3.0

The latter LDC99T42 (Penn Treebank Dataset)

You can also read https://github.com/hankcs/TreebankPreprocessing.git for help if you need to preprocessing the PTB dataset.

**Comment by insomnia1996** [comment]
> > treebank 3.0
> 
> The latter LDC99T42 (Penn Treebank Dataset)
> 
> You can also read https://github.com/hankcs/TreebankPreprocessing.git for help if you need to preprocessing the PTB dataset.

Thanks again for your helping :)
